# Generated by Django 3.2.18 on 2024-02-29 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='course_name',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
        migrations.AlterField(
            model_name='courses',
            name='credit_hours',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
